### ISSUE TITLE
Error on iOS app

### ISSUE THREAD

**Issue by sowo** [indico/indico-checkin#39]
When using the indico-checkin iOS app with our local Indico instance, the app produces an error on all actions:

![image](https://github.com/indico/indico-checkin/assets/2765941/80a463bc-c1a3-403f-88f6-297acd01327f)

The Android version of the app works fine with the same backend Indico instance.

**Comment by ThiefMaster** [comment]
can you check your indico log file if there's were any failing requests at the time you got the error, and to which url those requests were sent? it looks like something caused an HTML response where the app expected JSON.

**Comment by sowo** [comment]
I did check the logs and did not see any errors. One thing that might be of relevance is that we are using Cloudflare in front of our Indico instance. But I don't see how that might affect iOS only.

**Comment by ThiefMaster** [comment]
maybe you hit cloudflare's bot protection? do they have logs?

**Comment by sowo** [comment]
I will check with our CF admins but doubt that we can get any insight from there. Is there any way to display the HTML response? Or can we emulate the request from e.g. Postman (incl. all the headers you use) to see what's wrong?

**Comment by ThiefMaster** [comment]
probably runnings a dev version of the app would allow you to do that. you probably need a mac for this, and personally i have zero knowledge on iOS development (besides not having a mac)

**Comment by sowo** [comment]
`personally i have zero knowledge on iOS development (besides not having a mac)`

we are in the same boat :(

**Comment by sowo** [comment]
This error seems to have originated from an intermittent cloudflare issue.
