### ISSUE TITLE
Feature request: Alphabetical sorting of attendees

### ISSUE THREAD

**Issue by Yasharah** [indico/indico-checkin#5]
Hello,
We had our first event with the indico website and the check in app. It turned out that for an easier use of the app  one feature would be important: The participants should be sorted alphabetically and / or a search function should be included.

It would be great if that would be possible in the future.

**Comment by driehle** [comment]
Both alphabetical sorting and a search function are implemented in pull request #8 :-)

**Comment by pferreir** [comment]
Closing since #8 (#16) has been merged.
